library(hugene20sttranscriptcluster.db)
library(oligo)
library(FactoMineR)
require(factoextra)
library(EnhancedVolcano)
library(dorothea)
library(viper)
library(rlist)
library(data.table)
library(stringr)
library(matrixStats)
library(pheatmap)

