---
title: "R Notebook"
output: html_notebook
---

# INITIALISATION

```{r, include=FALSE}
source("functions.R")
BMIQ_list <- list()
Phenotypes <- list()
Results <- list()
Gene_ontology <- list()
source("Initialisation.R")
```

## DATA IMPORT

```{r}
load("../DATA/Methyl_DATA_Wang_Feng.RData")
load("../DATA/Wang_Feng_RNAseq.RData")
Phenotypes[["Koichi_cohort"]] <- read.csv("../DATA/Patient_phenotype_Koichi_cohort.csv")
```

# Methylation analysis

## Baseline Non_Responder vs Responder

```{r}
data_subset <- Phenotypes[["Koichi_cohort"]][ , c("Baseline_phenotype", "Baseline_Sample")]  

Patient_Baseline_with_treatment_annotation <- Phenotypes[["Koichi_cohort"]][complete.cases(data_subset), ]
rm(data_subset)
BMIQ_list[["Baseline_Methylation"]] <- dplyr::select(BMIQ_Wang_Feng, Patient_Baseline_with_treatment_annotation$Baseline_Sample)

Phenotypes[["Baseline_Methylation"]] <- data.frame("Sample" = Patient_Baseline_with_treatment_annotation$Baseline_Sample, "Phenotype" = Patient_Baseline_with_treatment_annotation$Baseline_phenotype)

Overlap_data[["EPIC_CpG_chromatin_enhancer_Koichi"]] <- Overlap_data[["EPIC_CpG_chromatin_enhancer"]] %>%
  dplyr::filter(., CpG %in% rownames(BMIQ_list[["Baseline_Methylation"]]))

tmp_data[["CpGs_EPIC_Non_Promoter_Koichi"]] <- Overlap_data[["EPIC_CpG_chromatin_enhancer_Koichi"]]$CpG %>%
  unique(.)
```

### Enhancer Koichi preparation

```{r}
BMIQ_list[["Koichi_Methylation_Non_promoter"]] <- BMIQ_Wang_Feng %>%
  dplyr::filter(., rownames(.) %in% tmp_data[["CpGs_EPIC_Non_Promoter_Koichi"]])

CpGs_per_fragment[["EPIC_Koichi"]] <- Overlap_data[["EPIC_CpG_chromatin_enhancer_Koichi"]] %>%
  dplyr::select(., c("CpG", "ID")) %>%
  split(., Overlap_data[["EPIC_CpG_chromatin_enhancer_Koichi"]]$ID)

part1 <- CpGs_per_fragment[["EPIC_Koichi"]][c(1:20000)]

part1 <- lapply(part1, function(fragment){
  tmp <- BMIQ_list[["Koichi_Methylation_Non_promoter"]][fragment$CpG,] %>%
    as.matrix(.)
  if (length(tmp[,1])>1){
    tmp <- t(colMeans2(tmp))
    colnames(tmp) <- colnames(BMIQ_list[["Koichi_Methylation_Non_promoter"]])
  }
  as.data.frame(tmp)
})
system("say part one finished")
part2 <- CpGs_per_fragment[["EPIC_Koichi"]][c(20001:40000)]

part2 <- lapply(part2, function(fragment){
  tmp <- BMIQ_list[["Koichi_Methylation_Non_promoter"]][fragment$CpG,] %>%
    as.matrix(.)
  if (length(tmp[,1])>1){
    tmp <- t(colMeans2(tmp))
    colnames(tmp) <- colnames(BMIQ_list[["Koichi_Methylation_Non_promoter"]])
  }
  as.data.frame(tmp)
})
system("say part two finished")
part3 <- CpGs_per_fragment[["EPIC_Koichi"]][c(40001:60000)]

part3 <- lapply(part3, function(fragment){
  tmp <- BMIQ_list[["Koichi_Methylation_Non_promoter"]][fragment$CpG,] %>%
    as.matrix(.)
  if (length(tmp[,1])>1){
    tmp <- t(colMeans2(tmp))
    colnames(tmp) <- colnames(BMIQ_list[["Koichi_Methylation_Non_promoter"]])
  }
  as.data.frame(tmp)
})

system("say part three finished")

part4 <- CpGs_per_fragment[["EPIC_Koichi"]][c(60001:68371)]

part4 <- lapply(part4, function(fragment){
  tmp <- BMIQ_list[["Koichi_Methylation_Non_promoter"]][fragment$CpG,] %>%
    as.matrix(.)
  if (length(tmp[,1])>1){
    tmp <- t(colMeans2(tmp))
    colnames(tmp) <- colnames(BMIQ_list[["Koichi_Methylation_Non_promoter"]])
  }
  as.data.frame(tmp)
})

system("say finished finished finished")

CpGs_per_fragment[["Means_EPIC_Koichi"]] <- c(part1, part2, part3, part4)

saveRDS(CpGs_per_fragment[["Means_EPIC_Koichi"]], "../DATA/Means_Cpgs_Koichi_per_fragment.RDS")
```

### Promoter

```{r}
Results[["Basline_methylation_promoter"]] <- T_test_on_methylation_promoter(BMIQ = BMIQ_list[["Baseline_Methylation"]], 
                                                                            Phenotype = Phenotypes[["Baseline_Methylation"]],
                                                                            match_hit_CpGs_Blueprint_promoter = Overlap_data[["EPIC_Blueprint_promoter"]],
                                                                            comparison = c("Non_Responder", "Responder"))

```

### Enhancer

```{r}
Samples <- colnames(CpGs_per_fragment[["Means_EPIC_Koichi"]][["1_172895418"]]) 

A <- sapply(Samples, function(x){
  tmp <- dplyr::filter(Phenotypes[["Koichi_cohort"]], Baseline_phenotype == "Non_Responder")
  x %in% tmp$Baseline_Sample
}) %>% as.vector(.)
B <- sapply(Samples, function(x){
  tmp <- dplyr::filter(Phenotypes[["Koichi_cohort"]], Baseline_phenotype == "Responder")
  x %in% tmp$Baseline_Sample
}) %>% as.vector(.)

comparison <- list()
comparison[[1]] <- A
comparison[[2]] <- B

Results[["Baseline_enhancer_analysis"]] <- T_test_on_methylation_enhancer(Mean_CpGs_per_fragment = CpGs_per_fragment[["Means_EPIC_Koichi"]], 
                               comparisons = comparison, 
                               Fragment_connected_per_gene = Overlap_data[["Fragment_connected_per_gene"]])

Results[["Baseline_enhancer_analysis"]][["Genes_list_of_Genes_with_hyper_enhancers_annoted"]] %>% write.csv(., "../Results/Tables report/Baseline_enhancer_analysis_genes_hyper.csv")

```

## After treatment Non_responder vs Responder


```{r}
data_subset <- Phenotypes[["Koichi_cohort"]][ , c("Baseline_phenotype", "Post_treatment_sample")]  

Patient_post_treatment_with_treatment_annotation <- Phenotypes[["Koichi_cohort"]][complete.cases(data_subset), ]
rm(data_subset)
BMIQ_list[["Post_Methylation"]] <- dplyr::select(BMIQ_Wang_Feng, Patient_post_treatment_with_treatment_annotation$Post_treatment_sample)

Phenotypes[["Post_Methylation"]] <- data.frame("Sample" = Patient_Baseline_with_treatment_annotation$Post_treatment_sample, "Phenotype" = Patient_Baseline_with_treatment_annotation$Baseline_phenotype)
```

### Promoter

```{r}
Results[["Post_methylation_promoter"]] <- T_test_on_methylation_promoter(BMIQ = BMIQ_list[["Post_Methylation"]], 
                                                                            Phenotype = Phenotypes[["Post_Methylation"]],
                                                                            match_hit_CpGs_Blueprint_promoter = Overlap_data[["EPIC_Blueprint_promoter"]],
                                                                            comparison = c("Non_Responder", "Responder"))
```

### Enhancer

```{r}
A <- sapply(Samples, function(x){
  tmp <- dplyr::filter(Phenotypes[["Koichi_cohort"]], Baseline_phenotype == "Non_Responder")
  x %in% tmp$Post_treatment_sample
}) %>% as.vector(.)
B <- sapply(Samples, function(x){
  tmp <- dplyr::filter(Phenotypes[["Koichi_cohort"]], Baseline_phenotype == "Responder")
  x %in% tmp$Post_treatment_sample
}) %>% as.vector(.)

comparison <- list()
comparison[[1]] <- A
comparison[[2]] <- B

Results[["After_treatment_enhancer_analysis"]] <- T_test_on_methylation_enhancer(Mean_CpGs_per_fragment = CpGs_per_fragment[["Means_EPIC_Koichi"]], 
                               comparisons = comparison, 
                               Fragment_connected_per_gene = Overlap_data[["Fragment_connected_per_gene"]])

Results[["After_treatment_enhancer_analysis"]][["Genes_list_of_Genes_with_hyper_enhancers_annoted"]] %>% write.csv(., "../Results/Tables report/After_treatment_enhancer_analysis_genes_hyper.csv")
```

# Gene expression


```{r}
A <- sapply(colnames(RNAseq_Wang_Feng), function(x){
  tmp <- dplyr::filter(Phenotypes[["Koichi_cohort"]], Baseline_phenotype == "Non_Responder")
  x %in% tmp$Baseline_RNAseq_data
})

B <- sapply(colnames(RNAseq_Wang_Feng), function(x){
  tmp <- dplyr::filter(Phenotypes[["Koichi_cohort"]], Baseline_phenotype == "Responder")
  x %in% tmp$Baseline_RNAseq_data
})

RNAseq_Wang_Feng_Baseline <- RNAseq_Wang_Feng %>%
  .[,A | B]

C <- sapply(colnames(RNAseq_Wang_Feng_Baseline), function(x){
  tmp <- dplyr::filter(Phenotypes[["Koichi_cohort"]], Baseline_phenotype == "Non_Responder")
  x %in% tmp$Baseline_RNAseq_data
})

D <- sapply(colnames(RNAseq_Wang_Feng_Baseline), function(x){
  tmp <- dplyr::filter(Phenotypes[["Koichi_cohort"]], Baseline_phenotype == "Responder")
  x %in% tmp$Baseline_RNAseq_data
})

tmp <- data.frame("Non_responder" = C, "Responder" = D)
tmp$Phenotype <- ifelse(C, "Non_responder", ifelse(D, "Responder", "No_data"))

ann_color_RNA <- list(
    Phenotype = c(Responder = "blue", Non_responder = "red", No_data = "grey"))

png("../Results/Heatmap_RNAseq_Baseline.png")
Make_heatmap(RNAseq_Wang_Feng_Baseline, tmp, "pearson", "Non_responder & Responder", ann_color_RNA)
dev.off()

heatmap_Baseline <- Make_heatmap(RNAseq_Wang_Feng_Baseline, tmp, "pearson", "Non_responder & Responder", ann_color_RNA)

# colnames(RNAseq_Wang_Feng)[heatmap_Baseline$tree_col[["order"]]][c(1:15)]
# 
# batch = c(rep("A", 15), rep("B", 51-15))
# 
# combat_edata1 = ComBat(dat=RNAseq_Wang_Feng, batch=batch, mod=NULL, par.prior=TRUE, prior.plots=FALSE)
# 
# Make_heatmap(combat_edata1, tmp, "pearson", "Non_responder & Responder", ann_color_RNA)

RNAseq_Wang_Feng_Baseline_analysis <- Differential_analysis(tmp$Phenotype, RNAseq_Wang_Feng_Baseline)

# RNAseq_Wang_Feng_Baseline_analysis_batch1_corrected <- Differential_analysis(tmp$Phenotype, combat_edata1)
```

```{r}
Genes_methylation <- Results[["Basline_methylation_promoter"]]$Genes_methylation_analysis
colnames(Genes_methylation) <- c("Gene_name", "Methylation_p.value", "Mean_NR_methylation", "Mean_R_methylation", "delta_methylation")

Genes_expression <- RNAseq_Wang_Feng_Baseline_analysis[["Non_responder-Responder"]]
Genes_expression$ID <- Genes_expression$ID %>% str_split(., "[|]") %>% lapply(., function(x){
  x[1]
}) %>%
  unlist(.)

# Genes_expression_batch_corrected <- RNAseq_Wang_Feng_Baseline_analysis_batch1_corrected[["Non_responder-Responder"]]
# Genes_expression_batch_corrected$ID <- Genes_expression_batch_corrected$ID %>% str_split(., "[|]") %>% lapply(., function(x){
#   x[1]
# }) %>%
#   unlist(.)

Gene_methyl_expression_data <- merge(Genes_expression, Genes_methylation, by.x = "ID", by.y = "Gene_name", all = TRUE)
Gene_methyl_expression_data_both_annotations <- merge(Genes_expression, Genes_methylation, by.x = "ID", by.y = "Gene_name")

Genes_hypermethylated_NR_vs_R <- Gene_methyl_expression_data_both_annotations %>%
  dplyr::filter(., delta_methylation > 0.1 & Methylation_p.value < 0.1)

Genes_hypomethylated_NR_vs_R <- Gene_methyl_expression_data_both_annotations %>%
  dplyr::filter(., delta_methylation < -0.1 & Methylation_p.value < 0.1)

Genes_Hypermethylated_suppressed <- Gene_methyl_expression_data_both_annotations %>%
  dplyr::filter(., delta_methylation > 0.1 & logFC < -0.75 & P.Value < 0.1 & Methylation_p.value < 0.1)

Genes_Hypomethylated_upregulated <-  Gene_methyl_expression_data_both_annotations %>%
  dplyr::filter(., delta_methylation < -0.1 & logFC > 0.75 & P.Value < 0.1 & Methylation_p.value < 0.1)

Genes_Hypermethylated_upregulated <- Gene_methyl_expression_data_both_annotations %>%
  dplyr::filter(., delta_methylation > 0.1 & logFC > 0.75 & P.Value < 0.1 & Methylation_p.value < 0.1)

Genes_Hypomethylated_suppressed <-  Gene_methyl_expression_data_both_annotations %>%
  dplyr::filter(., delta_methylation < -0.1 & logFC < -0.75 & P.Value < 0.1 & Methylation_p.value < 0.1)


###############

# Gene_methyl_expression_data_batch_corrected <- merge(Genes_expression_batch_corrected, Genes_methylation, by.x = "ID", by.y = "Gene_name", all = TRUE)
# 
# Genes_hypermethylated_NR_vs_R_batch_corrected <- Gene_methyl_expression_data_batch_corrected %>%
#   dplyr::filter(., delta_methylation > 0.1 & Methylation_p.value < 0.1)
# 
# Genes_hypomethylated_NR_vs_R_batch_corrected <- Gene_methyl_expression_data_batch_corrected %>%
#   dplyr::filter(., delta_methylation < -0.1 & Methylation_p.value < 0.1)
# 
# Genes_Hypermethylated_suppressed_batch_corrected <- Gene_methyl_expression_data_batch_corrected %>%
#   dplyr::filter(., delta_methylation > 0.1 & logFC < -0.75 & P.Value < 0.1 & Methylation_p.value < 0.1)
# 
# Genes_Hypomethylated_upregulated_batch_corrected <-  Gene_methyl_expression_data_batch_corrected %>%
#   dplyr::filter(., delta_methylation < -0.1 & logFC > 0.75 & P.Value < 0.1 & Methylation_p.value < 0.1)
# 
# Genes_Hypermethylated_upregulated_batch_corrected <- Gene_methyl_expression_data_batch_corrected %>%
#   dplyr::filter(., delta_methylation > 0.1 & logFC > 0.75 & P.Value < 0.1 & Methylation_p.value < 0.1)
# 
# Genes_Hypomethylated_suppressed_batch_corrected <-  Gene_methyl_expression_data_batch_corrected %>%
#   dplyr::filter(., delta_methylation < -0.1 & logFC < -0.75 & P.Value < 0.1 & Methylation_p.value < 0.1)
```

```{r}
Number_Genes_Hypermethylated_no_changes <- length(Genes_hypermethylated_NR_vs_R$ID) - length(Genes_Hypermethylated_upregulated$ID) - length(Genes_Hypermethylated_suppressed$ID)

Number_Genes_Hypomethylated_no_changes <- length(Genes_hypomethylated_NR_vs_R$ID) - length(Genes_Hypomethylated_upregulated$ID) - length(Genes_Hypomethylated_suppressed$ID)

Numbers <- c(length(Genes_Hypermethylated_upregulated$ID), 
             Number_Genes_Hypermethylated_no_changes, 
             length(Genes_Hypermethylated_suppressed$ID), 
             length(Genes_Hypomethylated_upregulated$ID), 
             Number_Genes_Hypomethylated_no_changes, 
             length(Genes_Hypomethylated_suppressed$ID))


Barplot_data <- data.frame(Gene_expression=rep(c("up_regulated", "no_changes", "down_regulated"), 2),
                           Methylation=rep(c("Hypermethylated", "Hypomethylated"), each = 3),
                           Number_of_genes = Numbers)

ggplot(data=Barplot_data, aes(x=Methylation, y=Number_of_genes, fill=Gene_expression)) +
  geom_bar(stat="identity")
ggsave("~/correlation_methylation_expression.png")
```

```{r}
Genes_up <- Gene_methyl_expression_data_both_annotations %>% 
  dplyr::filter(., logFC > 0.75 & P.Value < 0.05) %>%
  .$ID

Genes_hyper <- Gene_methyl_expression_data_both_annotations %>% 
  dplyr::filter(., Methylation_p.value < 0.05 & delta_methylation > 0.1) %>%
  .$ID

Genes_hypo <- Gene_methyl_expression_data_both_annotations %>% 
  dplyr::filter(., Methylation_p.value < 0.05 & delta_methylation < -0.1) %>%
  .$ID

Genes_down <- Gene_methyl_expression_data_both_annotations %>% 
  dplyr::filter(., logFC < -0.75 & P.Value < 0.05) %>%
  .$ID

Venn_promoter_diagramm <- list(
  "Hyper" = Genes_hyper,
  "Down" = Genes_down,
  "UP" = Genes_up,
  "Hypo" = Genes_hypo
)
library(ggvenn)
ggvenn(
  Venn_promoter_diagramm, 
  fill_color = c("#0073C2FF", "#EFC000FF", "#868686FF", "#CD534CFF"))
ggsave("~/Venn_expression_methylation_promoter.png")
```

```{r}
Genes_up <- Gene_methyl_expression_data_both_annotations %>% 
  dplyr::filter(., logFC > 0.75 & P.Value < 0.05) %>%
  .$ID

Genes_DM <- Gene_methyl_expression_data_both_annotations %>% 
  dplyr::filter(., Methylation_p.value < 0.05 & abs(delta_methylation) > 0.1) %>%
  .$ID

Genes_down <- Gene_methyl_expression_data_both_annotations %>% 
  dplyr::filter(., logFC < -0.75 & P.Value < 0.05) %>%
  .$ID

Venn_promoter_diagramm <- list(
  "DM" = Genes_DM,
  "Down" = Genes_down,
  "UP" = Genes_up
)
library(ggvenn)
ggvenn(
  Venn_promoter_diagramm, 
  fill_color = c("#EFC000FF", "#868686FF", "#CD534CFF"))
ggsave("~/Venn_expression_Dmethylation_promoter.png")

```


### Enhancer

```{r}
tmp <- names(Results[["Baseline_enhancer_analysis"]][["Enhancer_summary"]])
  
Gene_enhancer_methylation_analysis <- rbindlist(Results[["Baseline_enhancer_analysis"]][["Enhancer_summary"]]) %>% as.data.frame(.)
rownames(Gene_enhancer_methylation_analysis) <- tmp

Gene_methyl_enhancer_expression_data <- merge(Genes_expression, Gene_enhancer_methylation_analysis, by.x = "ID", by.y = 0)

Gene_methyl_enhancer_expression_data$logFC <- ifelse(Gene_methyl_enhancer_expression_data$logFC > 1, log10(Gene_methyl_enhancer_expression_data$logFC),  ifelse(Gene_methyl_enhancer_expression_data$logFC < -1, -log10(-Gene_methyl_enhancer_expression_data$logFC), Gene_methyl_enhancer_expression_data$logFC))

Gene_methyl_enhancer_expression_data$nb_enhancer_changed <- Gene_methyl_enhancer_expression_data$nb_enhancer_hyper + Gene_methyl_enhancer_expression_data$nb_enhancer_hypo
```


```{r}
nb_enhancer_treshold <- 0

Number_Genes_Hypermethylated_no_changes <- Gene_methyl_enhancer_expression_data %>% 
  dplyr::filter(., nb_enhancer_hyper > nb_enhancer_treshold & (P.Value > 0.05 | abs(logFC) < 0.75)) %>%
  .$ID %>%
  length()
  
Number_Genes_Hypermethylated_enh_suppressed <- Gene_methyl_enhancer_expression_data %>% 
  dplyr::filter(., nb_enhancer_hyper > nb_enhancer_treshold & P.Value < 0.05 & logFC < -0.75) %>%
  .$ID %>%
  length()

Number_Genes_Hypermethylated_enh_surrexpressed <- Gene_methyl_enhancer_expression_data %>% 
  dplyr::filter(., nb_enhancer_hyper > nb_enhancer_treshold & P.Value < 0.05 & logFC > 0.75) %>%
  .$ID %>%
  length()

Number_Genes_Hypomethylated_no_changes <- Gene_methyl_enhancer_expression_data %>% 
  dplyr::filter(., nb_enhancer_hypo > nb_enhancer_treshold & (P.Value > 0.05 | abs(logFC)) < 0.75) %>%
  .$ID %>%
  length()
  
Number_Genes_Hypomethylated_enh_suppressed <- Gene_methyl_enhancer_expression_data %>% 
  dplyr::filter(., nb_enhancer_hypo > nb_enhancer_treshold & P.Value < 0.05 & logFC < -0.75) %>%
  .$ID %>%
  length()

Number_Genes_Hypomethylated_enh_surrexpressed <- Gene_methyl_enhancer_expression_data %>% 
  dplyr::filter(., nb_enhancer_hypo > nb_enhancer_treshold & P.Value < 0.05 & logFC > 0.75) %>%
  .$ID %>%
  length()

Numbers <- c(Number_Genes_Hypermethylated_enh_suppressed, 
             Number_Genes_Hypermethylated_no_changes, 
             Number_Genes_Hypermethylated_enh_surrexpressed, 
             Number_Genes_Hypomethylated_enh_suppressed, 
             Number_Genes_Hypomethylated_no_changes, 
             Number_Genes_Hypomethylated_enh_surrexpressed)


Barplot_data <- data.frame(Gene_expression=rep(c("down_regulated", "no_changes", "up_regulated"), 2),
                           Methylation=rep(c("Hypermethylated", "Hypomethylated"), each = 3),
                           Number_of_genes = Numbers)

ggplot(data=Barplot_data, aes(x=Methylation, y=Number_of_genes, fill=Gene_expression)) +
  geom_bar(stat="identity")
ggsave("~/correlation_methylation_enhancer_expression.png")
```

```{r}
nb_enhancer_treshold <- 0

Genes_up <- Gene_methyl_enhancer_expression_data %>% 
  dplyr::filter(., logFC > 0.75 & P.Value < 0.05) %>%
  .$ID

Genes_hyper <- Gene_methyl_enhancer_expression_data %>% 
  dplyr::filter(., nb_enhancer_hyper > nb_enhancer_treshold) %>%
  .$ID

Genes_hypo <- Gene_methyl_enhancer_expression_data %>% 
  dplyr::filter(., nb_enhancer_hypo > nb_enhancer_treshold) %>%
  .$ID

Genes_down <- Gene_methyl_enhancer_expression_data %>% 
  dplyr::filter(., logFC < -0.75 & P.Value < 0.05) %>%
  .$ID

Venn_promoter_diagramm <- list(
  "Hyper" = Genes_hyper,
  "Down" = Genes_down,
  "UP" = Genes_up,
  "Hypo" = Genes_hypo
)
library(ggvenn)
ggvenn(
  Venn_promoter_diagramm, 
  fill_color = c("#0073C2FF", "#EFC000FF", "#868686FF", "#CD534CFF"))
ggsave("~/Venn_expression_methylation_enhancer.png")
```

```{r}
nb_enhancer_treshold <- 0

Genes_up <- Gene_methyl_enhancer_expression_data %>% 
  dplyr::filter(., logFC > 0.75 & P.Value < 0.05) %>%
  .$ID

Genes_DM <- Gene_methyl_enhancer_expression_data %>% 
  dplyr::filter(., nb_enhancer_hyper > nb_enhancer_treshold | nb_enhancer_hypo > nb_enhancer_treshold) %>%
  .$ID

Genes_down <- Gene_methyl_enhancer_expression_data %>% 
  dplyr::filter(., logFC < -0.75 & P.Value < 0.05) %>%
  .$ID

Venn_promoter_diagramm <- list(
  "DM" = Genes_DM,
  "Down" = Genes_down,
  "UP" = Genes_up
)

genes_DM_DE <- c(Genes_down, Genes_up) %>% 
  intersect(., Genes_DM) %>%
  length()

genes_no_DM_DE <- c(Genes_down, Genes_up) %>%
  length()
genes_no_DM_DE <- genes_no_DM_DE - genes_DM_DE

genes_DM_noDE <- Genes_DM %>%
  length()
genes_DM_noDE <- genes_DM_noDE - genes_DM_DE

genes_no_DM_noDE <- Gene_methyl_enhancer_expression_data$ID %>%
  unique(.) %>%
  length()
genes_no_DM_noDE <- genes_no_DM_noDE - genes_DM_noDE - genes_no_DM_DE - genes_DM_DE

library(ggvenn)
ggvenn(
  Venn_promoter_diagramm, 
  fill_color = c("#EFC000FF", "#868686FF", "#CD534CFF"))
ggsave("~/Venn_expression_Dmethylation_enhancer.png")



table_fisher_test <- data.frame("Methylated_enhancer" = c(genes_DM_DE, genes_DM_noDE), "unmethylated_enhancer" = c(genes_no_DM_DE, genes_no_DM_noDE))
rownames(table_fisher_test) <- c("DE", "no DE")

fisher.test(table_fisher_test)
```

```{r}
Genes_up_DM <- Gene_methyl_enhancer_expression_data %>% dplyr::filter(., logFC > 1 & P.Value < 0.05 & (nb_enhancer_hyper > nb_enhancer_treshold | nb_enhancer_hypo > nb_enhancer_treshold))
Genes_down_DM <- Gene_methyl_enhancer_expression_data %>% dplyr::filter(., logFC < -1 & P.Value < 0.05 & (nb_enhancer_hyper > nb_enhancer_treshold | nb_enhancer_hypo > nb_enhancer_treshold))

Gene_enhancer_DM_expression <- rbind(Genes_up_DM, Genes_down_DM)
Gene_enhancer_DM_expression$logFC <- ifelse(Gene_enhancer_DM_expression$logFC > 1, log10(Gene_enhancer_DM_expression$logFC),  -log10(-Gene_enhancer_DM_expression$logFC))

Gene_enhancer_DM_expression <- dplyr::filter(Gene_enhancer_DM_expression, abs(logFC) > 0.75)

write.csv(Gene_enhancer_DM_expression, "../Results/Tables report/Gene lists/Gene_enhancer_DM_expression.csv", row.names = FALSE)
```


```{r}
Gene_methyl_enhancer_expression_data_target_gene <- dplyr::filter(Gene_methyl_enhancer_expression_data, ID %in% c(Genes_Hypermethylated_suppressed$ID, Genes_Hypomethylated_suppressed$ID))

nb_enhancer_treshold <- 1

Number_Genes_Hypermethylated_no_changes <- Gene_methyl_enhancer_expression_data_target_gene %>% 
  dplyr::filter(., nb_enhancer_hyper > nb_enhancer_treshold & (P.Value > 0.05 | abs(logFC) < 0.75)) %>%
  .$ID %>%
  length()
  
Number_Genes_Hypermethylated_enh_suppressed <- Gene_methyl_enhancer_expression_data_target_gene %>% 
  dplyr::filter(., nb_enhancer_hyper > nb_enhancer_treshold & P.Value < 0.05 & logFC < -0.75) %>%
  .$ID %>%
  length()

Number_Genes_Hypermethylated_enh_surrexpressed <- Gene_methyl_enhancer_expression_data_target_gene %>% 
  dplyr::filter(., nb_enhancer_hyper > nb_enhancer_treshold & P.Value < 0.05 & logFC > 0.75) %>%
  .$ID %>%
  length()

Number_Genes_Hypomethylated_no_changes <- Gene_methyl_enhancer_expression_data_target_gene %>% 
  dplyr::filter(., nb_enhancer_hypo > nb_enhancer_treshold & (P.Value > 0.05 | abs(logFC)) < 0.75) %>%
  .$ID %>%
  length()
  
Number_Genes_Hypomethylated_enh_suppressed <- Gene_methyl_enhancer_expression_data_target_gene %>% 
  dplyr::filter(., nb_enhancer_hypo > nb_enhancer_treshold & P.Value < 0.05 & logFC < -0.75) %>%
  .$ID %>%
  length()

Number_Genes_Hypomethylated_enh_surrexpressed <- Gene_methyl_enhancer_expression_data_target_gene %>% 
  dplyr::filter(., nb_enhancer_hypo > nb_enhancer_treshold & P.Value < 0.05 & logFC > 0.75) %>%
  .$ID %>%
  length()

Numbers <- c(Number_Genes_Hypermethylated_enh_suppressed, 
             Number_Genes_Hypermethylated_no_changes, 
             Number_Genes_Hypermethylated_enh_surrexpressed, 
             Number_Genes_Hypomethylated_enh_suppressed, 
             Number_Genes_Hypomethylated_no_changes, 
             Number_Genes_Hypomethylated_enh_surrexpressed)


Barplot_data <- data.frame(Gene_expression=rep(c("down_regulated", "no_changes", "up_regulated"), 2),
                           Methylation=rep(c("Hypermethylated", "Hypomethylated"), each = 3),
                           Number_of_genes = Numbers)

ggplot(data=Barplot_data, aes(x=Methylation, y=Number_of_genes, fill=Gene_expression)) +
  geom_bar(stat="identity")
ggsave("~/correlation_methylation_enhancer_promoter_expression.png")
```

```{r}
Genes_hypermethylated_analysis <- Gene_methyl_expression_data_both_annotations %>% 
  dplyr::filter(., Methylation_p.value < 0.1 & delta_methylation > 0.1)

enhancedvolcano_data1 <- data.frame(FC = Genes_hypermethylated_analysis$logFC,
                                    p.value = Genes_hypermethylated_analysis$P.Value,
                                    gene = Genes_hypermethylated_analysis$ID)

enhancedvolcano_data1$logFC <- ifelse(enhancedvolcano_data1$FC > 0, log(enhancedvolcano_data1$FC), -log(-enhancedvolcano_data1$FC))

EnhancedVolcano(toptable = enhancedvolcano_data1,
                lab = enhancedvolcano_data1$gene,
                x = "logFC",
                y = "p.value",
                FCcutoff = 0.75,
                pCutoff = 0.1,
                ylim = c(0, 5),
                xlim = c(-15,15)
                )
ggsave("../Results/correlation_hypermetylation_expression.png")

Genes_hypermethylated_analysis %>% 
  dplyr::filter(., logFC < -0.75 & P.Value < 0.1) %>%
  .$ID %>%
  write.csv(., "../Results/Tables report/Gene lists/Genes_hypermeth_suppressed.csv", row.names = FALSE)

Genes_hypermethylated_analysis %>% 
  dplyr::filter(., logFC > 0.75 & P.Value < 0.1) %>%
  .$ID %>%
  write.csv(., "../Results/Tables report/Gene lists/Genes_hypermeth_surressed.csv", row.names = FALSE)
```


```{r}
Genes_hypomethylated_analysis <- Gene_methyl_expression_data_both_annotations %>% 
  dplyr::filter(., Methylation_p.value < 0.05 & delta_methylation < -0.1)

enhancedvolcano_data2 <- data.frame(FC = Genes_hypomethylated_analysis$logFC,
                                    p.value = Genes_hypomethylated_analysis$P.Value,
                                    gene = Genes_hypomethylated_analysis$ID)

enhancedvolcano_data2$logFC <- ifelse(enhancedvolcano_data2$FC > 0, log(enhancedvolcano_data2$FC), -log(-enhancedvolcano_data2$FC))

EnhancedVolcano(toptable = enhancedvolcano_data2,
                lab = enhancedvolcano_data2$gene,
                x = "logFC",
                y = "p.value",
                FCcutoff = 0.75,
                pCutoff = 0.05,
                ylim = c(0, 5),
                xlim = c(-15,15)
                )
ggsave("~/correlation_hypomethylation_expression.png")

Genes_hypomethylated_analysis %>% 
  dplyr::filter(., logFC > 0.75 & P.Value < 0.1) %>%
  .$ID %>%
  write.csv(., "../Results/Tables report/Gene lists/Genes_hypometh_surressed.csv", row.names = FALSE)

Genes_hypomethylated_analysis %>% 
  dplyr::filter(., logFC < -0.75 & P.Value < 0.1) %>%
  .$ID %>%
  write.csv(., "../Results/Tables report/Gene lists/Genes_hypometh_suppressed.csv", row.names = FALSE)
```

```{r}
Gene_methyl_enhancer_expression_data_target_gene <- dplyr::filter(Gene_methyl_enhancer_expression_data, ID %in% c(Genes_hypermethylated_analysis$ID, Genes_hypomethylated_analysis$ID))

nb_enhancer_treshold <- 1

Number_Genes_Hypermethylated_no_changes <- Gene_methyl_enhancer_expression_data_target_gene %>% 
  dplyr::filter(., nb_enhancer_hyper > nb_enhancer_treshold & (P.Value > 0.05 | abs(logFC) < 0.75)) %>%
  .$ID %>%
  length()
  
Number_Genes_Hypermethylated_enh_suppressed <- Gene_methyl_enhancer_expression_data_target_gene %>% 
  dplyr::filter(., nb_enhancer_hyper > nb_enhancer_treshold & P.Value < 0.05 & logFC < -0.75) %>%
  .$ID %>%
  length()

Number_Genes_Hypermethylated_enh_surrexpressed <- Gene_methyl_enhancer_expression_data_target_gene %>% 
  dplyr::filter(., nb_enhancer_hyper > nb_enhancer_treshold & P.Value < 0.05 & logFC > 0.75) %>%
  .$ID %>%
  length()

Number_Genes_Hypomethylated_no_changes <- Gene_methyl_enhancer_expression_data_target_gene %>% 
  dplyr::filter(., nb_enhancer_hypo > nb_enhancer_treshold & (P.Value > 0.05 | abs(logFC)) < 0.75) %>%
  .$ID %>%
  length()
  
Number_Genes_Hypomethylated_enh_suppressed <- Gene_methyl_enhancer_expression_data_target_gene %>% 
  dplyr::filter(., nb_enhancer_hypo > nb_enhancer_treshold & P.Value < 0.05 & logFC < -0.75) %>%
  .$ID %>%
  length()

Number_Genes_Hypomethylated_enh_surrexpressed <- Gene_methyl_enhancer_expression_data_target_gene %>% 
  dplyr::filter(., nb_enhancer_hypo > nb_enhancer_treshold & P.Value < 0.05 & logFC > 0.75) %>%
  .$ID %>%
  length()

Numbers <- c(Number_Genes_Hypermethylated_enh_suppressed, 
             Number_Genes_Hypermethylated_no_changes, 
             Number_Genes_Hypermethylated_enh_surrexpressed, 
             Number_Genes_Hypomethylated_enh_suppressed, 
             Number_Genes_Hypomethylated_no_changes, 
             Number_Genes_Hypomethylated_enh_surrexpressed)


Barplot_data <- data.frame(Gene_expression=rep(c("down_regulated", "no_changes", "up_regulated"), 2),
                           Methylation=rep(c("Hypermethylated", "Hypomethylated"), each = 3),
                           Number_of_genes = Numbers)

ggplot(data=Barplot_data, aes(x=Methylation, y=Number_of_genes, fill=Gene_expression)) +
  geom_bar(stat="identity")
```


```{r}
methyl_enhancer_ge_corr <- data.frame(logFC = Gene_methyl_enhancer_expression_data$logFC,
                                      nb_enhancer_hypermethyl = Gene_methyl_enhancer_expression_data$nb_enhancer_hyper,
                                      gene = Gene_methyl_enhancer_expression_data$ID)

methyl_enhancer_ge_corr$logFC_GE <- ifelse(methyl_enhancer_ge_corr$logFC > 0, log(methyl_enhancer_ge_corr$logFC), -log(-methyl_enhancer_ge_corr$logFC))

plot(x = methyl_enhancer_ge_corr$logFC_GE, y = methyl_enhancer_ge_corr$nb_enhancer_hypermethyl)
```


### logFC GE vs FC Met

```{r}
Genes_analysis <- Gene_methyl_expression_data_both_annotations %>%
  dplyr::filter(., Methylation_p.value < 0.05 & P.Value < 0.05)

methyl_ge_corr <- data.frame(logFC_M = Genes_analysis$delta_methylation,
                                    FC_GE = Genes_analysis$logFC,
                                    gene = Genes_analysis$ID)

methyl_ge_corr$logFC_GE <- ifelse(methyl_ge_corr$FC_GE > 0, log(methyl_ge_corr$FC_GE), -log(-methyl_ge_corr$FC_GE))

png("test2.png")
plot(x = methyl_ge_corr$logFC_M, y = methyl_ge_corr$logFC_GE)
dev.off()
plot(x = methyl_ge_corr$logFC_M, y = methyl_ge_corr$logFC_GE)
```

# After treatment

```{r}
A <- sapply(colnames(RNAseq_Wang_Feng), function(x){
  tmp <- dplyr::filter(Phenotypes[["Koichi_cohort"]], Baseline_phenotype == "Non_Responder")
  x %in% tmp$Baseline_RNAseq_data
})

B <- sapply(colnames(RNAseq_Wang_Feng), function(x){
  tmp <- dplyr::filter(Phenotypes[["Koichi_cohort"]], Baseline_phenotype == "Responder")
  x %in% tmp$Relapse_RNAseq_data
})

tmp_after <- data.frame("Non_responder" = A, "Responder" = B)
tmp_after$Phenotype <- ifelse(A, "Non_responder", ifelse(B, "Responder", "No_data"))

ann_color_RNA <- list(
    Phenotype = c(Responder = "blue", Non_responder = "red", No_data = "grey"))

png("../Results/Heatmap_RNAseq_relapse.png")
Make_heatmap(RNAseq_Wang_Feng, tmp_after, "pearson", "Non_responder & Responder", ann_color_RNA)
dev.off()

heatmap_Relapse <- Make_heatmap(RNAseq_Wang_Feng, tmp_after, "pearson", "Non_responder & Responder", ann_color_RNA)

colnames(RNAseq_Wang_Feng)[heatmap_Baseline$tree_col[["order"]]][c(1:15)]

batch = c(rep("A", 15), rep("B", 51-15))

combat_edata1 = ComBat(dat=RNAseq_Wang_Feng, batch=batch, mod=NULL, par.prior=TRUE, prior.plots=FALSE)

Make_heatmap(combat_edata1, tmp_after, "pearson", "Non_responder & Responder", ann_color_RNA, cuttree = 2)

RNAseq_Wang_Feng_Baseline_analysis <- Differential_analysis(tmp_after$Phenotype, RNAseq_Wang_Feng)
```

# TF analysis

```{r}
RNAseq_Baselin_rownames <- RNAseq_Wang_Feng_Baseline


RNAseq_Baselin_rownames$Gene <- rownames(RNAseq_Baselin_rownames) %>% str_split(., "[|]") %>% lapply(., function(x){
  x[1]
}) %>%
  unlist(.)

RNAseq_Baselin_rownames <- RNAseq_Baselin_rownames %>%
  split(., .$Gene) %>%
  lapply(., function(x){
    l <- length(x[1,]) - 1
    cnames <- colnames(x)[c(1:l)]
    df <- x[,c(1:l)] %>%
      as.matrix(.) %>%
      colSums2(.) %>% 
      data.frame(.) %>%
      t(.) %>%
      data.frame(.)
    colnames(df) <- cnames
    df
  }) %>%
  rbindlist(.) %>% 
  data.frame(.)

gene_rownames <- rownames(RNAseq_Wang_Feng_Baseline) %>% str_split(., "[|]") %>% lapply(., function(x){
  x[1]
}) %>%
  unlist(.) %>% 
  unique(.)
rownames(RNAseq_Baselin_rownames) <- gene_rownames

data(dorothea_hs, package = "dorothea")
regulons = dorothea_hs %>%
  filter(confidence %in% c("A", "B"))
tf_activities <- run_viper(RNAseq_Baselin_rownames, regulons, 
                           options =  list(method = "scale", minsize = 4, eset.filter = FALSE, cores = 1, verbose = FALSE))
tf_activities=t(tf_activities) %>% as.data.frame()
rownames(tf_activities) <- substr(rownames(tf_activities), 2, 11)
palette_length = 100
my_color = colorRampPalette(c("Darkblue", "white","red"))(palette_length)

Clustering_Baseline_phenotype <- read.csv("~/GitHub/Epigenomic_integration/DATA/Wang_Feng_DATA/Clustering_Baseline_phenotype.csv")

rownames(Clustering_Baseline_phenotype) <- Clustering_Baseline_phenotype$UPN

tmp$Cluster <- rownames(tmp) %>% 
  substr(., 1, 7) %>%
  Clustering_Baseline_phenotype[.,] %>%
  .$Cluster
  
tmp$Cluster[which(is.na(tmp$Cluster))] <- "No_data"

colnames(tmp) <- c("Non_Responder", "Responder", "Phenotype", "Cluster")

annotation_heatmap <- data.frame("Phenotype" = tmp$Phenotype,
                                 "Clusters" = tmp$Cluster)
rownames(annotation_heatmap) <- rownames(tmp)

ann_color_RNA <- list(
    Phenotype = c(Responder = "blue", Non_responder = "red", No_data = "grey"),
    Clusters = c(cluster1 = "blue", cluster2 = "red", No_data = "grey"))

corr_TF <- rcorr(as.matrix(t(tf_activities)), type = "pearson")$r
png("../Results/tf_activities.png", height = 1080, width = 1920)
pheatmap(tf_activities, col = viridis::inferno(50), column_title = "Transcription Factor activities", annotation_row = annotation_heatmap, annotation_colors = ann_color_RNA)
dev.off()

png("../Results/Corr_patient_tf.png", height = 1080, width = 1920)
pheatmap(corr_TF, annotation_row = annotation_heatmap, annotation_colors = ann_color_RNA)
dev.off()
pheatmap(tf_activities, col = viridis::inferno(50), column_title = "Transcription Factor activities", annotation_row = annotation_heatmap, annotation_colors = ann_color_RNA)
pheatmap(corr_TF, annotation_row = annotation_heatmap, annotation_colors = ann_color_RNA)

```
```{r}
DATA_for_PCA <- RNAseq_Baselin_rownames
DATA_for_PCA <- DATA_for_PCA %>%
  t() %>%
  as.matrix()

res.pca <- PCA(DATA_for_PCA, graph = TRUE)

fviz_eig(res.pca, addlabels = TRUE)

fviz_pca_ind(res.pca,
             geom.ind = "point", # Montre les points seulement (mais pas le "text")
             col.ind = tmp$Phenotype, # colorer by groups
             palette = c("#00AFBB", "#E7B800", "#FC4E07"),
             addEllipses = TRUE, # Ellipses de concentration
             legend.title = "Groups"
             )

```


```{r}
t= Heatmap(t(tf_activities), col = viridis::inferno(50), row_km = 4, column_split = colnames(t(tf_activities)), row_gap = unit(5, "mm"))

gse= enrichGO(colnames(tf_activities[,row_order(ht)$'4']),OrgDb = org.Hs.eg.db,keyType = "SYMBOL")
```


```{r}
A <- sapply(rownames(tf_activities), function(x){
  tmp <- dplyr::filter(Phenotypes[["Koichi_cohort"]], Baseline_phenotype == "Non_Responder")
  x %in% tmp$Baseline_RNAseq_data
})

B <- sapply(rownames(tf_activities), function(x){
  tmp <- dplyr::filter(Phenotypes[["Koichi_cohort"]], Baseline_phenotype == "Responder")
  x %in% tmp$Baseline_RNAseq_data
})

test <- tf_activities[,c(1:2)]

tf_Ttest_activities <- tf_activities %>%
  sapply(., function(x){
    test_tmp <- t.test(x[A], x[B])
    c("p.value_activities" = test_tmp$p.value, 
               "Non_reponder_mean" = test_tmp$estimate[1], 
               "Responder" = test_tmp$estimate[2])
  }) %>%
  t()
  

write.csv(tf_Ttest_activities, file = "../Results/tf_Ttest_activities.csv")


RNAseq_Wang_Feng_Baseline_analysis[["Non_responder-Responder"]]$ID <- rownames(RNAseq_Wang_Feng_Baseline_analysis[["Non_responder-Responder"]]) %>% str_split(., "[|]") %>% lapply(., function(x){
  x[1]
}) %>%
  unlist(.)

TF_activity_expression <- merge(tf_Ttest_activities, RNAseq_Wang_Feng_Baseline_analysis[["Non_responder-Responder"]], by.x = 0, by.y = "ID", all.x = TRUE)

TF_activity_expression$logFC <- ifelse(TF_activity_expression$logFC > 1, log(TF_activity_expression$logFC), ifelse(TF_activity_expression$logFC < -1 , -log(-TF_activity_expression$logFC), TF_activity_expression$logFC))

TF_activity_expression %>% .[order(.$p.value_activities),] %>% write.csv("../Results/TF_activities_expression.csv", row.names = FALSE)
```



```{r}
Non_responder_tf_activities <- tf_activities %>%
  .[rownames(tmp)[tmp$Phenotype == "Non_responder"],] %>%
  as.matrix(.) %>%
  colMeans2(.) %>%
  as.data.frame(.)

Responder_tf_activities <- tf_activities %>%
  .[rownames(tmp)[tmp$Phenotype == "Responder"],] %>%
  as.matrix(.) %>%
  colMeans2(.) %>%
  as.data.frame(.)

Tf_activities_phenotype <- data.frame("Non_Responder" = Non_responder_tf_activities, 
                                      "Responder" = Responder_tf_activities)
rownames(Tf_activities_phenotype) <- colnames(tf_activities)
colnames(Tf_activities_phenotype) <- c("Non_responder", "Responder")

Tf_activities_phenotype$delta <- Tf_activities_phenotype$Non_responder - Tf_activities_phenotype$Responder


write.csv(regulons, file = "../DATA/regulons.csv", row.names = FALSE)
write.csv(Tf_activities_phenotype, file = "../Results/Tf_activitiess_NR_R.csv")
```

# MS VIPER

```{r}
ref <- which(tmp$Phenotype == "Responder")

ref_name <- "Responder"
treat_name <- "Non_Responder"

msviper_results <- run_msviper(as.matrix(RNAseq_Baselin_rownames), regulons, use_aracne = T, ref, ref_name, treat_name, minsize = 4, ges.filter = T)

original_gene_list <- RNAseq_Wang_Feng_Baseline_analysis[["Non_responder-Responder"]]$logFC

names(original_gene_list) <- RNAseq_Wang_Feng_Baseline_analysis[["Non_responder-Responder"]]$ID

gene_list<-na.omit(original_gene_list)

gene_list = gene_list[RNAseq_Wang_Feng_Baseline_analysis[["Non_responder-Responder"]]$P.Value<=0.05]

gene_list = sort(gene_list, decreasing = TRUE)

expre = data.frame("TF"=names(gene_list),"LogFC"=paste(gene_list)  )

msviper_results$mrs_table = left_join(msviper_results$mrs_table,expre,by="TF")
msviper_results$mrs_table= replace( msviper_results$mrs_table, is.na( msviper_results$mrs_table), '0') 
msviper_results$mrs_table$LogFC=  as.numeric(msviper_results$mrs_table$LogFC) 

all_nodes <- unique(c(msviper_results$regulons$tf, msviper_results$regulons$target))
tnodes <- tibble(TF = all_nodes)
all_nodes_metadata <- right_join(msviper_results$mrs_table, tnodes, by = "TF")
all_nodes_metadata$LogFC= RNAseq_Wang_Feng_Baseline_analysis[["Non_responder-Responder"]]$logFC[match(all_nodes_metadata$TF,RNAseq_Wang_Feng_Baseline_analysis[["Non_responder-Responder"]]$ID)]

TF = na.exclude(all_nodes_metadata$TF[all_nodes_metadata$pval<0.1]) %>% paste()

data_stat = msviper_results$regulons[msviper_results$regulons$tf%in%TF,]

res_TF <- RNAseq_Wang_Feng_Baseline_analysis[["Non_responder-Responder"]] %>%
                  dplyr::filter(., ID %in% unique(data_stat$target))
res_TF= res_TF[res_TF$P.Value<0.05,]

original_gene_list <- res_TF$logFC

# name the vector
names(original_gene_list) <- (rownames(res_TF))

# omit any NA values 
gene_list<-na.omit(original_gene_list)


gene_list = sort(gene_list, decreasing = TRUE)

```


