---
title: "R Notebook"
output: html_notebook
---

```{r}
setwd("~/GitHub/Epigenomic_integration/")
source("Scripts/packages.R")
#source("Scripts/functions.R")
```


```{r}
load("../pchic.RData")
pchic <- data.frame(pchic[rowSums(pchic[,11:20] >= 7) >= 1, 1:10]) %>% na.omit(.)
List_Promoter <- unique(paste(pchic$baitChr, pchic$baitStart, sep = "_"))
colnames(pchic)[c(1:5, 6:10)] <- rep(c("chr", "start", "end", "ID", "Name"), 2)
PCHiC_bed <- unique(rbind(pchic[, c(1:3, 5)], pchic[, c(6:8, 10)]))
PCHiC_GRange <- GRanges(
  seqnames = PCHiC_bed$chr,
  IRanges(start = PCHiC_bed$start, end = PCHiC_bed$end),
  Gene_Pchic = PCHiC_bed$Name,
  start_fragment = PCHiC_bed$start,
  end_fragment = PCHiC_bed$end
)
PCHiC_GRange$ID <- paste(PCHiC_bed$chr, PCHiC_bed$start, sep = "_")
colnames(pchic) <- c("chr_bait", "start_bait", "end_bait", "ID_bait", "Name_bait", "chr_oe", "start_oe", "end_oe", "ID_oe", "Name_oe")
pchic$IDbait <- paste(pchic$chr_bait, pchic$start_bait, sep = "_")
pchic$IDoe <- paste(pchic$chr_oe, pchic$start_oe, sep = "_")

load("../CD34_enhancer_bed.RData")
CD34_enhancer_Granges <- GRanges(
  seqnames = CD34_enhancer_bed$CHR,
  ranges = IRanges(start = CD34_enhancer_bed$start, end = CD34_enhancer_bed$end),
  value = CD34_enhancer_bed$value
)
overlaps_pchic_CD34_enhancer <- findOverlaps(PCHiC_GRange, CD34_enhancer_Granges)
match_hit_pchic_CD34_enhancer <- data.frame(mcols(PCHiC_GRange[queryHits(overlaps_pchic_CD34_enhancer),]),
                                       data.frame(mcols(CD34_enhancer_Granges[subjectHits(overlaps_pchic_CD34_enhancer),])))

load("../AML_enhancer_bed.RData")
AML_enhancer_Granges <- GRanges(
  seqnames = AML_enhancer_bed$CHR,
  ranges = IRanges(start = AML_enhancer_bed$start, end = AML_enhancer_bed$end),
  value = AML_enhancer_bed$value
)
overlaps_pchic_AML_enhancer <- findOverlaps(PCHiC_GRange, AML_enhancer_Granges)
match_hit_pchic_AML_enhancer <- data.frame(mcols(PCHiC_GRange[queryHits(overlaps_pchic_AML_enhancer),]),
                                       data.frame(mcols(AML_enhancer_Granges[subjectHits(overlaps_pchic_AML_enhancer),])))


Blueprint <- read.csv("../BLUEPRINT_fragments_good.tsv", sep = "\t") %>%
  dplyr::select(., "gene_names":"type", "gene_type") %>%
  separate_rows(., gene_names, sep = " ") %>%
  separate_rows(., gene_type, sep = " ") %>%
  unique(.)

anno <- read.csv("~/Illumina_manifest/HumanMethylation450_15017482_v1-2.csv", skip = 7) %>% 
  dplyr::select(., "Name", "CHR", "MAPINFO", "UCSC_RefGene_Name", "UCSC_RefGene_Group", "Relation_to_UCSC_CpG_Island") %>%
  dplyr::filter(., CHR != "") %>%
  separate_rows(., UCSC_RefGene_Name, UCSC_RefGene_Group, sep = ";")

Blueprint_Granges <- GRanges(
    seqnames = Blueprint$chr,
    ranges = IRanges(start = Blueprint$start, end = Blueprint$end),
    Blueprint_gene_names = Blueprint$gene_names,
    type = Blueprint$type,
    gene_type = Blueprint$gene_type
  )
CpGs_Granges <- GRanges(
  seqnames = anno$CHR,
  ranges = IRanges(anno$MAPINFO, anno$MAPINFO +1),
  CpG = anno$Name,
  Illumina_Gene_name = anno$UCSC_RefGene_Name,
  position = anno$UCSC_RefGene_Group,
  Island = anno$Relation_to_UCSC_CpG_Island
)
overlaps_CpGs_Blueprint <- findOverlaps(Blueprint_Granges, CpGs_Granges)
match_hit_CpGs_Blueprint <- data.frame(mcols(Blueprint_Granges[queryHits(overlaps_CpGs_Blueprint),]),
                                       data.frame(mcols(CpGs_Granges[subjectHits(overlaps_CpGs_Blueprint),])))

overlaps_CpGs_Pchic <- findOverlaps(CpGs_Granges, PCHiC_GRange)
matchit_CpGs_Pchic <- data.frame(mcols(CpGs_Granges[queryHits(overlaps_CpGs_Pchic),]),
                                       data.frame(mcols(PCHiC_GRange[subjectHits(overlaps_CpGs_Pchic),])))
matchit_CpGs_Pchic$CD34_enhancer <- ifelse(matchit_CpGs_Pchic$ID %in% match_hit_pchic_CD34_enhancer$ID, "CD34_enhancer", "not_referenced")

```

```{r}
gene_list <- c("CEBPA", "CPT1A", "CPT2", "SLC25A20", "AKT1", "AKT2", "AKT3", "PPARGC1A", "PTEN")

BMIQ_met <- read.csv("~/GitHub/TCGA_Connections/BMIQ_met.csv", row.names=1)

BMIQ_all <- merge(BMIQ_met, BMIQ_CD34, by.x = 0, by.y = 0)
rownames(BMIQ_all) <- BMIQ_all$Row.names
BMIQ_all <- BMIQ_all[,-1]

Phenotype <- data.frame("Sample" = colnames(BMIQ_all),"Phenotype" = ifelse(colnames(BMIQ_all) %in% colnames(BMIQ_IDHm), "IDHm", 
                    ifelse(colnames(BMIQ_all) %in% colnames(BMIQ_CD34), "CD34", "IDHWT")))

debugg <- Focus_gene_neighborhood("CEBPA", BMIQ_all, matchit_blueprint = match_hit_CpGs_Blueprint, matchit_pchic = matchit_CpGs_Pchic, Phenotype_df = Phenotype, title = "Neighbor_Promoter_methylation_IDHWT_CD34_IDHWT")

for (i in gene_list){
  Focus_gene_neighborhood(i, BMIQ_all, matchit_blueprint = match_hit_CpGs_Blueprint, matchit_pchic = matchit_CpGs_Pchic, Phenotype_df = Phenotype, title = "Neighbor_Promoter_methylation_IDHWT_CD34_IDHWT")
}
```

```{r}
TS <- Phenotype$Phenotype
TS <- factor(TS, levels = c("CD34", "IDHm", "IDHWT"))
design <- model.matrix(~ 0 + TS)
colnames(design) <- levels(TS)
fit <- lmFit(BMIQ_all, design)

cont.matrix <- makeContrasts(
  IDHm_vs_CD34 = CD34 - IDHm,
  IDHm_vs_IDHWT = IDHm - IDHWT,
  IDHWT_vs_CD34 = IDHWT - CD34,
  levels = design
)
fit.contrast <- contrasts.fit(fit, cont.matrix)
efit.contrast <- eBayes(fit.contrast)

filtered_DMP_IDHmvsCD34 <- data.frame(logFC = efit.contrast[["coefficients"]][,1], pvalue = efit.contrast[["p.value"]][,1]) %>%
  dplyr::filter(., logFC > 0.3 | logFC < -0.3) %>%
  dplyr::filter(., pvalue < 0.01) %>%
  merge(., BMIQ_all, by.x = 0, by.y = 0)
rownames(filtered_DMP_IDHmvsCD34) <- filtered_DMP_IDHmvsCD34$Row.names
filtered_DMP_IDHmvsCD34 <- filtered_DMP_IDHmvsCD34[,-1]

filtered_DMPIDHmvsIDHWT <- data.frame(logFC = efit.contrast[["coefficients"]][,2], pvalue = efit.contrast[["p.value"]][,2]) %>%
  dplyr::filter(., logFC > 0.3 | logFC < -0.3) %>%
  dplyr::filter(., pvalue < 0.01) %>%
  merge(., BMIQ_all, by.x = 0, by.y = 0)
rownames(filtered_DMPIDHmvsIDHWT) <- filtered_DMPIDHmvsIDHWT$Row.names
filtered_DMPIDHmvsIDHWT <- filtered_DMPIDHmvsIDHWT[,-1]

filtered_DMPIDHWT_vs_CD34 <- data.frame(logFC = efit.contrast[["coefficients"]][,3], pvalue = efit.contrast[["p.value"]][,3]) %>%
  dplyr::filter(., logFC > 0.3 | logFC < -0.3) %>%
  dplyr::filter(., pvalue < 0.01) %>%
  merge(., BMIQ_all, by.x = 0, by.y = 0)
rownames(filtered_DMPIDHWT_vs_CD34) <- filtered_DMPIDHWT_vs_CD34$Row.names
filtered_DMPIDHWT_vs_CD34 <- filtered_DMPIDHWT_vs_CD34[,-1]

for (i in gene_list){
  Focus_gene_neighborhood(i, BMIQ_all, match_hit_CpGs_Blueprint, matchit_CpGs_Pchic, "Promoter_neighborhood_IDHmvsCD34_differential_methylation", Phenotype, filtered_DMP_IDHmvsCD34, diff = TRUE)
}
for (i in gene_list){
  Focus_gene_neighborhood(i, BMIQ_all, match_hit_CpGs_Blueprint, matchit_CpGs_Pchic, "Promoter_neighborhood_IDHmvsIDHWT_differential_methylation", Phenotype, filtered_DMPIDHmvsIDHWT, diff = TRUE)
}
for (i in gene_list){
  Focus_gene_neighborhood(i, BMIQ_all, match_hit_CpGs_Blueprint, matchit_CpGs_Pchic, "Promoter_neighborhood_IDHWT_vs_CD34_differential_methylation", Phenotype, filtered_DMPIDHWT_vs_CD34, diff = TRUE)
}



```


